const fixtures = [
  {
    name: 'Mark',
    home: 'London',
    hobbies: 'Tennis, programming, going out',
    work: 'Programmer',
    origin: 'Manchester',
    additional: 'Cool guy',
  },
  {
    name: 'Sarah',
    home: 'New York',
    hobbies: 'Tennis, programming, going out',
    work: 'Programmer',
    origin: 'San Fransisco',
    additional: 'Cool girl',
  },
  {
    name: 'Mark',
    home: 'London',
    hobbies: 'Tennis, programming, going out',
    work: 'Programmer',
    origin: 'Leamington Spa',
    additional: 'Cool guy',
  },
  {
    name: 'Sarah',
    home: 'New York',
    hobbies: 'Tennis, programming, going out',
    work: 'Programmer',
    origin: 'San Fransisco',
    additional: 'Cool girl',
  },
  {
    name: 'Mark',
    home: 'London',
    hobbies: 'Tennis, programming, going out',
    work: 'Programmer',
    origin: 'Leamington Spa',
    additional: 'Cool guy',
  },
  {
    name: 'Sarah',
    home: 'New York',
    hobbies: 'Tennis, programming, going out',
    work: 'Programmer',
    origin: 'San Fransisco',
    additional: 'Cool girl',
  },
  {
    name: 'Mark',
    home: 'London',
    hobbies: 'Tennis, programming, going out',
    work: 'Programmer',
    origin: 'Leamington Spa',
    additional: 'Cool guy',
  },
  {
    name: 'Sarah',
    home: 'New York',
    hobbies: 'Tennis, programming, going out',
    work: 'Programmer',
    origin: 'San Fransisco',
    additional: 'Cool girl',
  },
  {
    name: 'Mark',
    home: 'London',
    hobbies: 'Tennis, programming, going out',
    work: 'Programmer',
    origin: 'Leamington Spa',
    additional: 'Cool guy',
  },
  {
    name: 'Sarah',
    home: 'New York',
    hobbies: 'Tennis, programming, going out',
    work: 'Programmer',
    origin: 'San Fransisco',
    additional: 'Cool girl',
  },
  {
    name: 'Mark',
    home: 'London',
    hobbies: 'Tennis, programming, going out',
    work: 'Programmer',
    origin: 'Leamington Spa',
    additional: 'Cool guy',
  },
  {
    name: 'Sarah',
    home: 'New York',
    hobbies: 'Tennis, programming, going out',
    work: 'Programmer',
    origin: 'San Fransisco',
    additional: 'Cool girl',
  },
];

export default fixtures;
